### ISSUE TITLE
Is this only for virtual cameras?

### ISSUE THREAD

**Issue by BrianGilbert** [friesofdoom/FriesBSCam#7]
All the examples I’ve seen are using avatars in LIV, just wondering if this will work with real cameras?

**Comment by friesofdoom** [comment]
I've never considered how this would work on real cameras, so I wouldn't exactly count on it.

**Comment by sepffuzzball** [comment]
It would certainly be interesting (and really cool) to do a Mixed Reality camera plugin where you could have multiple cameras and switch between them dynamically versus having a dedicated camera person and tracker to move the camera...but I don't think that's something that makes sense for this plugin!
